#!/bin/bash
# script 1: Write a script that will "import" the public key from a locally created key pair into your AWS account.

KEY_NAME="bcitkey"
PUB_KEY_PATH="$HOME/.ssh/${KEY_NAME}.pub"

aws ec2 import-key-pair --key-name "$KEY_NAME"  --public-key-material fileb://"$PUB_KEY_PATH"




